# Generated by Django 4.1.9 on 2024-03-23 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallepedido',
            name='user',
        ),
    ]
