# Generated by Django 4.1.9 on 2024-04-13 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0003_producto_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='informacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=40, null=True)),
                ('descripcion', models.TextField(null=True)),
            ],
        ),
    ]
