# Generated by Django 4.2.6 on 2024-03-22 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0003_pedido_detallepedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='session_token',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
