# Generated by Django 4.2.6 on 2024-03-07 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0003_carrito_categoria_alter_sliderimage_title_producto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='especial',
            field=models.BooleanField(default=False, verbose_name='Producto especial'),
        ),
    ]
