# Generated by Django 4.2.6 on 2024-03-22 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0004_pedido_session_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='session_token',
        ),
    ]
