# Generated by Django 4.1.9 on 2024-04-19 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0004_informacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacion',
            name='direccion',
            field=models.TextField(null=True),
        ),
    ]
