# Generated by Django 4.1.9 on 2024-04-19 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0005_informacion_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacion',
            name='numero',
            field=models.IntegerField(null=True),
        ),
    ]
