# Generated by Django 4.1.9 on 2024-04-19 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0006_informacion_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacion',
            name='numero',
            field=models.TextField(null=True),
        ),
    ]
