# Generated by Django 4.1.9 on 2024-04-21 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0007_alter_informacion_numero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metodos_pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('otro', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='descripcion',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='metodo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Productos.metodos_pago'),
        ),
    ]
