# Generated by Django 4.1.9 on 2024-04-21 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0008_metodos_pago_pedido_descripcion_pedido_metodo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='metodo',
        ),
    ]
