# Generated by Django 4.1.9 on 2024-04-21 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0009_remove_pedido_descripcion_remove_pedido_metodo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metodos_pago',
            name='otro',
        ),
        migrations.AddField(
            model_name='pedido',
            name='descripcion',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='metodo_pago',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Productos.metodos_pago'),
        ),
    ]
