# Generated by Django 4.1.9 on 2024-04-21 22:48

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0010_remove_metodos_pago_otro_pedido_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='default-slug', editable=False, populate_from='nombre', unique=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='descripcion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
