# Generated by Django 4.1.9 on 2024-04-21 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0012_alter_pedido_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='slug',
        ),
    ]
