# Generated by Django 4.1.9 on 2024-04-21 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0014_alter_pedido_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='disponible',
            field=models.BooleanField(default=False, verbose_name='Producto no disponible'),
        ),
    ]
